version: '3'
services:
    db:
        image: mysql:5.7 
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test_database
            MYSQL_USER: admin
            MYSQL_PASSWORD: adminpass
            TZ: 'Asia/Tokyo'
    java:
        image: openjdk:11
        ports:
            - 8080:8080
        tty: true
        depends_on:
            - db